# Generated by Django 3.2.7 on 2021-09-11 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoenixapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='firstName',
            field=models.CharField(default='wow', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='lastName',
            field=models.CharField(default='wow', max_length=200),
            preserve_default=False,
        ),
    ]
